# Site settings
baseurl: "/twomillion" # on Github Pages, change when this goes live
creator: "The Awesome Foundation"
description: "We've given out two million dollars in grants!"
email: ""
github_username:  ""
logo: "/images/logo.png"
subject: "Awesome Foundation"
title: "$2 million of Awesome Foundation!"
twitter_username: "@awesomefound"
url: "http://awesomefoundation.org"
copyright: "The Awesome Foundation 2016"

gaTracking: ""

gems: ["jekyll-less"]