# Site settings
baseurl: ""
creator: "The Awesome Foundation"
description: "We've given out over two million dollars in grants!"
email: ""
github_username:  ""
logo: "/images/logo.png"
social_logo: "/images/social-logo-2.png"
subject: "The Awesome Foundation"
title: "$2 million of Awesome Foundation!"
twitter_username: "@awesomefound"
url: "http://twomillion.awesomefoundation.org"
copyright: "The Awesome Foundation 2016"

gaTracking: ""

gems: ["jekyll-less"]